# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(894, 655)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(680, 120, 121, 51))
        self.pushButton.setObjectName("pushButton")
        self.mytest_label = QtWidgets.QLabel(Form)
        self.mytest_label.setGeometry(QtCore.QRect(160, 80, 101, 31))
        self.mytest_label.setObjectName("mytest_label")

        self.mytest_textedit = QtWidgets.QTextEdit(Form)
        self.mytest_textedit.setGeometry(QtCore.QRect(130, 170, 201, 51))
        self.mytest_textedit.setObjectName("mytest_textedit")

        self.textEdit_row1inplate = QtWidgets.QTextEdit(Form)
        self.textEdit_row1inplate.setGeometry(QtCore.QRect(110, 150, 81, 31))
        self.textEdit_row1inplate.setObjectName("textEdit_row1inplate")

        self.retranslateUi(Form)
        self.pushButton.clicked.connect(Form.my_fist_button_test)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "PushButton"))
        self.mytest_label.setText(_translate("Form", "fucktest"))
